<link href="{{url('/admin-assets/images/icons/apple-touch-icon-144-precomposed.png')}}" rel="apple-touch-icon-precomposed" sizes="144x144">
<link href="{{url('/admin-assets/images/icons/apple-touch-icon-114-precomposed.png')}}" rel="apple-touch-icon-precomposed" sizes="114x114">
<link href="{{url('/admin-assets/images/icons/apple-touch-icon-72-precomposed.png')}}" rel="apple-touch-icon-precomposed" sizes="72x72">
<link href="{{url('/admin-assets/images/icons/apple-touch-icon-57-precomposed.png')}}" rel="apple-touch-icon-precomposed">
<link href="{{url('/admin-assets/images/icons/favicon.png')}}" rel="shortcut icon">
<link href="{{url('/admin-assets/helpers/animate.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/boilerplate.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/grid.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/utils.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/colors.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/badges.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/dropdown/dropdown.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/content-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/components/border-radius.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/login-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/dashboard-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/icons/fontawesome/fontawesome.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/icons/linecons/linecons.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/mobile-navigation.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/admin/layout.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/admin/color-schemes/default.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/components/default.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/responsive-elements.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/admin-responsive.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/popover/popover.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/spacing.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/tooltip/tooltip.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/notification-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/border-radius.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/page-transitions.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/typography.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/material/ripple.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/forms.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/images.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/info-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/invoice.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/loading-indicators.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/menus.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/panel-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/response-messages.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/responsive-tables.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/ribbon.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/social-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/tables.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/tile-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/timeline.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/icons/spinnericon/spinnericon.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/accordion-ui/accordion.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/calendar/calendar.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/carousel/carousel.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/charts/justgage/justgage.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/charts/morris/morris.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/charts/piegage/piegage.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/charts/xcharts/xcharts.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/chosen/chosen.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/colorpicker/colorpicker.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/datatable/datatable.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/datepicker/datepicker.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/nestable/nestable.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/noty-notifications/noty.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/pretty-photo/prettyphoto.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/progressbar/progressbar.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/range-slider/rangeslider.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/slidebars/slidebars.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/slider-ui/slider.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/summernote-wysiwyg/summernote-wysiwyg.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/tabs-ui/tabs.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/timepicker/timepicker.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/tocify/tocify.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/touchspin/touchspin.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/uniform/uniform.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/wizard/wizard.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/xeditable/xeditable.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/chat.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/files-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/progress-box.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/todo.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/user-profile.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/applications/mailbox.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/buttons.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/css/workout.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/assets/plugins/select2/css/select2.css')}}" rel="stylesheet">
<link href="{{url('/assets/plugins/select2/css/select2-bootstrap.css')}}" rel="stylesheet">
<link href="{{url('/admin-assets/widgets/input-switch/inputswitch.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/assets/plugins/datetimepicker/css/DateTimePicker.css')}}" rel="stylesheet">
<link href="{{url('/assets/plugins/revolution-slider/css/revolution-slider.css')}}" rel="stylesheet">
<link href="{{url('/assets/plugins/owl-carousel-2.2.1/css/owl.carousel.css')}}" rel="stylesheet">
<link href="{{url('/assets/plugins/hover-2.1.1/css/hover.css')}}" rel="stylesheet">
<link href="{{url('/admin-assets/widgets/modal/modal.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/css/diet.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/datepicker-ui/datepicker.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/daterangepicker/daterangepicker.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/dialog/dialog.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/dropzone/dropzone.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/file-input/fileinput.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/input-switch/inputswitch-alt.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/ionrangeslider/ionrangeslider.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/jcrop/jcrop.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/jgrowl-notifications/jgrowl.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/loading-bar/loadingbar.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/maps/vector-maps/vectormaps.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/markdown/markdown.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/multi-select/multiselect.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/widgets/multi-upload/fileupload.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/assets/plugins/bootstrap-3.3.7/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">