<link href="{{url('/admin-assets/helpers/animate.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/boilerplate.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/grid.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/utils.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/colors.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/elements/badges.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/icons/fontawesome/fontawesome.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/icons/linecons/linecons.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/snippets/mobile-navigation.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/admin/layout.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/admin/color-schemes/default.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/themes/components/default.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/responsive-elements.css')}}" rel="stylesheet" type="text/css">
<link href="{{url('/admin-assets/helpers/admin-responsive.css')}}" rel="stylesheet" type="text/css">
